### ISSUE TITLE
dimensions in OAMaps

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-maps#79] opened 2021-05-27 16:18 UTC
In the MetOcean context, we need to consider addressing dimensions as part of OAMaps map rendering.  See the [OGC Best Practice for using Web Map Services (WMS) with Time- Dependent or Elevation-Dependent Data](https://portal.ogc.org/files/?artifact_id=56394), for the approach taken given the first generation of OGC web service standards.

Thoughts:

- a given collection would need to advertise its dimensions and their relevant extents (i.e. in a MetOcean/NWP context: model run/reference time, forecast  time, elevation/pressure level, etc.)
- the `.../map` payload could support `subset` accordingly
  - `subset=reference_time(YYYY-MM-DDThh:mm:ssZ),forecast_time(YYYY-MM-DDThh:mm:ssZ),pressure_level(1000mb)`
- we need to consider how `datetime` would be considered in OAMaps in general (i.e. server determined)
- much of this seems to be a good fit in the EDR context as well (in which case making a "map" conformance class may or may not make sense)
- we could also consider this as a 2D coverage with a web-friendly media type in OACov

cc @chris-little @jerstlouis @schpidi

**Comment by jerstlouis** [comment] 2022-08-04 17:16
This issue seems a duplicate of #16, with more discsusions here.

**Comment by joanma747** [comment] 2022-10-20 15:46
All aspects wil be covered by #16

**Closed by joanma747** 2022-10-20 15:46 UTC
Labels: 2021-05 Sprint
