### ISSUE TITLE
Extend the Maps API metadata model to include  a 'rel' to a map

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-maps#80] opened 2021-05-27 14:03 UTC
Maps API should extend the metadata model for the styles to include a 'rel' to a map.

**Comment by jerstlouis** [comment] 2022-02-13 21:42
I believe that we settled on how this should work, and only need to update the specification to reflect it.
(The title of the issue is confusing though, as this does not really concerns map metadata anymore).

**Comment by jerstlouis** [comment] 2022-08-04 16:12
[Requirement 21](http://docs.ogc.org/DRAFTS/20-058.html#_response_6) already includes the `http://www.opengis.net/def/rel/ogc/1.0/map` link relation, but also includes `map-meta` which may be obsolete. Can we get rid of this `map-meta`?

**Comment by jerstlouis** [comment] 2022-11-03 17:09
It seems that `map-meta` is gone already. Can we close this issue?

**Closed** 2022-11-03 18:56 UTC
Labels: 2021-05 Sprint
